// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Drives = sequelize.define('drives', {
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.literal('now()'),
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    deletedAt: {
      type: DataTypes.DATE,
    },
    duration: {
      type: DataTypes.INTEGER,
    },
    kilometers: {
      type: DataTypes.INTEGER,
    },
    incident: {
      type: DataTypes.BOOLEAN,
    },
  }, {
    tableName: 'drives',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Drives.associate = (models) => {
    Drives.belongsTo(models.agencies, {
      foreignKey: {
        name: 'agencyIdKey',
        field: 'agency_id',
      },
      as: 'agency',
    });
    Drives.belongsTo(models.cars, {
      foreignKey: {
        name: 'carIdKey',
        field: 'car_id',
      },
      as: 'car',
    });
    Drives.belongsTo(models.users, {
      foreignKey: {
        name: 'driverIdKey',
        field: 'driver_id',
      },
      as: 'driver',
    });
    Drives.belongsTo(models.driverLicences, {
      foreignKey: {
        name: 'driverLicenseIdKey',
        field: 'driver_license_id',
      },
      as: 'driverLicense',
    });
    Drives.belongsTo(models.users, {
      foreignKey: {
        name: 'moderatorIdKey',
        field: 'moderator_id',
      },
      as: 'moderator',
    });
  };

  return Drives;
};
